"""FertilizerRecommendation — Pillar 2 (XGBoost output).

Stores the NPK prescription, micronutrient flags, cost, and application
schedule generated by the XGBoost soil optimizer model.

Optionally paired with an IrrigationPlan via
IrrigationPlan.fertilizer_recommendation_id for the joint calendar.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class FertilizerRecommendation(Base):
    __tablename__ = "fertilizer_recommendations"

    recommendation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    farmer_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("farmers.farmer_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    soil_test_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("soil_tests.test_id", ondelete="SET NULL"),
        nullable=True,
    )
    crop_id: Mapped[str] = mapped_column(
        String(40),
        ForeignKey("crops.crop_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    season: Mapped[str | None] = mapped_column(String(20), nullable=True)
    acres: Mapped[float | None] = mapped_column(Numeric(5, 2), nullable=True)

    # NPK prescription (kg / acre)
    nitrogen_kg_per_acre: Mapped[float | None] = mapped_column(Numeric(6, 2), nullable=True)
    phosphorus_kg_per_acre: Mapped[float | None] = mapped_column(Numeric(6, 2), nullable=True)
    potassium_kg_per_acre: Mapped[float | None] = mapped_column(Numeric(6, 2), nullable=True)

    # Micronutrient flags + supplements
    # e.g. {"zinc_deficiency": true, "zinc_supplement": "Zinc sulphate 25 kg/ha",
    #        "iron_deficiency": false, "copper_deficiency": false, "boron_deficiency": false}
    micro_flags: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Cost analysis
    total_cost_estimate: Mapped[float | None] = mapped_column(Numeric(8, 2), nullable=True)
    savings_vs_standard: Mapped[float | None] = mapped_column(Numeric(8, 2), nullable=True)
    savings_note_ta: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Application schedule
    # e.g. [{"day": 1, "type": "basal", "notes": "Apply at transplanting"},
    #        {"day": 21, "type": "top_dress", "notes": "Split application"}]
    application_schedule: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list
    )

    # Provenance
    model_version: Mapped[str | None] = mapped_column(String(20), nullable=True)
    source: Mapped[str] = mapped_column(
        String(20), nullable=False, default="icar_baseline"
    )  # ml_model | icar_baseline | manual

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    farmer: Mapped["Farmer"] = relationship(
        "Farmer", back_populates="fertilizer_recommendations"
    )
    crop_ref: Mapped["Crop"] = relationship(
        "Crop", back_populates="fertilizer_recommendations"
    )
    soil_test: Mapped["SoilTest | None"] = relationship(
        "SoilTest", back_populates="fertilizer_recommendations"
    )
    irrigation_plan: Mapped["IrrigationPlan | None"] = relationship(
        "IrrigationPlan", back_populates="fertilizer_recommendation", uselist=False
    )
