"""IrrigationPlan — Pillar 2 (LSTM output).

Stores the 14-day irrigation schedule generated by the LSTM model,
including rain skips from IMD forecast and the joint fertilizer+irrigation
calendar when paired with a FertilizerRecommendation.
"""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, Integer, Numeric, String, func
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class IrrigationPlan(Base):
    __tablename__ = "irrigation_plans"

    plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    farmer_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("farmers.farmer_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    # Links to paired FertilizerRecommendation for joint calendar generation
    fertilizer_recommendation_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("fertilizer_recommendations.recommendation_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    crop_id: Mapped[str] = mapped_column(
        String(40),
        ForeignKey("crops.crop_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    start_date: Mapped[date] = mapped_column(Date, nullable=False)

    # Session schedule (14 days)
    # e.g. [{"day": 1, "date": "2025-07-01", "duration_min": 90,
    #         "volume_litres": 1800, "cost_estimate": 42.0}]
    schedule: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    total_sessions: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Dates where irrigation was skipped due to predicted rain (IMD)
    rain_skips: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)

    # Aggregate cost
    water_cost_estimate: Mapped[float | None] = mapped_column(Numeric(8, 2), nullable=True)

    # Joint fertilizer + irrigation calendar (only populated when paired)
    # e.g. [{"day": 1, "date": "...", "action": "irrigate", "detail": "90 min"},
    #        {"day": 2, "date": "...", "action": "fertilize", "detail": "Urea 1.8 kg"}]
    joint_calendar: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # IMD weather snapshot used to generate rain_skips
    weather_snapshot: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Provenance
    model_version: Mapped[str | None] = mapped_column(String(20), nullable=True)
    source: Mapped[str] = mapped_column(
        String(20), nullable=False, default="rule_based"
    )  # lstm_model | rule_based

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    farmer: Mapped["Farmer"] = relationship("Farmer", back_populates="irrigation_plans")
    crop_ref: Mapped["Crop"] = relationship("Crop", back_populates="irrigation_plans")
    fertilizer_recommendation: Mapped["FertilizerRecommendation | None"] = relationship(
        "FertilizerRecommendation", back_populates="irrigation_plan"
    )
