"""Seed the 24-scheme authoritative dataset into the main database.

NOTE: The preferred method is `alembic upgrade head` which runs migrations
005 and seeds all 24 schemes idempotently via ON CONFLICT DO UPDATE.
Use this script only when running Alembic is not possible.
"""
import asyncio
import sys

# Ensure stdout/stderr use UTF-8 so Tamil characters print correctly on Windows.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from datetime import date
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy.dialects.postgresql import insert as pg_insert
from app.db.models.scheme import GovernmentScheme

ENGINE = create_async_engine("postgresql+asyncpg://uzhavar:uzhavar@localhost:5432/uzhavar")
SessionLocal = async_sessionmaker(ENGINE, class_=AsyncSession, expire_on_commit=False)

D = date(2026, 6, 17)

SCHEMES = [
    # ── Central (level='central') ──────────────────────────────────────────────
    dict(scheme_id="CEN-PMKISAN",
         name_en="Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
         name_ta="பிரதம மந்திரி கிசான் சம்மான் நிதி", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="PM-KISAN", year="Ongoing",
         benefit_amount="₹6,000 per year in three installments of ₹2,000 each via Direct Benefit Transfer",
         benefit_amount_num=6000.0, min_land_acres=0.0, requires_aadhaar=True,
         documents_required=["Aadhaar card", "Land ownership records (Patta/Chitta)", "Bank account (Aadhaar-seeded, NEFT enabled)"],
         documents_ta=["ஆதார் அட்டை", "நில உரிமை ஆவணங்கள் (பட்டா/சிட்டா)", "வங்கி கணக்கு (ஆதார் இணைப்புடன்)"],
         application_url="https://pmkisan.gov.in",
         description_en="Provides direct income support to landholding farmer families to meet their agricultural and allied activity expenses. Fully funded by the Government of India.",
         description_ta="விவசாயக் குடும்பங்களுக்கு நேரடி வருமான உதவி. மூன்று தவணைகளில் ரூ.6,000 வழங்கப்படும்.",
         eligibility_en="Landholding farmer families (husband, wife, minor children) as per State/UT land records. Requires Aadhaar, e-KYC and land record validation.",
         eligibility_ta="நில உரிமையுள்ள விவசாய குடும்பங்கள். ஆதார் இணைப்பு மற்றும் e-KYC கட்டாயம்.",
         source_url="https://pmkisan.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-PMFBY",
         name_en="Pradhan Mantri Fasal Bima Yojana (PMFBY)",
         name_ta="பிரதம மந்திரி பயிர் காப்பீட்டுத் திட்டம்", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="PMFBY", year="Ongoing",
         benefit_amount="Crop insurance coverage. Farmer premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial/horticultural crops.",
         min_land_acres=0.0,
         documents_required=["Aadhaar card", "Land records or tenancy documents", "Bank account details", "Sowing certificate or crop declaration"],
         documents_ta=["ஆதார் அட்டை", "நில ஆவணங்கள் அல்லது குத்தகை ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்", "விதைப்பு சான்றிதழ் அல்லது பயிர் அறிவிப்பு"],
         application_url="https://pmfby.gov.in",
         description_en="Provides financial support to farmers suffering crop loss or damage due to natural calamities, pests and diseases.",
         description_ta="இயற்கை சீற்றங்கள், பூச்சிகள் மற்றும் நோய்களால் பயிர் இழப்பு ஏற்படும் விவசாயிகளுக்கு நிதி உதவி. இழப்பு 72 மணி நேரத்தில் தெரிவிக்க வேண்டும்.",
         eligibility_en="All farmers growing notified crops in notified areas. Voluntary participation.",
         eligibility_ta="அறிவிக்கப்பட்ட பகுதிகளில் அறிவிக்கப்பட்ட பயிர்கள் பயிரிடும் அனைத்து விவசாயிகளும். குத்தகை விவசாயிகளும் தகுதியுடையவர்கள்.",
         source_url="https://pmfby.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-PMKSY",
         name_en="Pradhan Mantri Krishi Sinchayee Yojana - Per Drop More Crop (PMKSY-PDMC)",
         name_ta="பிரதம மந்திரி கிரிஷி சின்சாயி யோஜனா - நுண்ணீர் பாசனம்", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="PMKSY-PDMC", year="Ongoing",
         benefit_amount="Subsidy on drip and sprinkler micro-irrigation systems. Commonly reported at 55% and above.",
         min_land_acres=0.0, max_land_acres=12.0,
         documents_required=["Aadhaar card", "Land records", "Bank account details", "Quotation for BIS-certified micro-irrigation equipment"],
         documents_ta=["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்", "BIS சான்றளிக்கப்பட்ட நுண்ணீர்ப்பாசன உபகரணங்களுக்கான மேற்கோள்"],
         application_url="https://pmksy.gov.in",
         description_en="Promotes micro-irrigation (drip and sprinkler) to enhance water use efficiency. Achieves 40-80% water savings.",
         description_ta="சொட்டு நீர் மற்றும் தெளிப்பு நீர்ப்பாசனம் மூலம் நீர் பயன்பாட்டு திறனை மேம்படுத்துதல். வழக்கமான பாசனத்தை விட 40-80% நீர் சேமிப்பு சாத்தியம்.",
         eligibility_en="All farmers. Subsidy limited to 5 hectares per beneficiary. Only BIS-certified components permitted.",
         eligibility_ta="அனைத்து மாநிலங்களிலும் உள்ள விவசாயிகள். ஒரு பயனாளிக்கு அதிகபட்சம் 5 எக்டர். BIS சான்றளிக்கப்பட்ட கூறுகள் கட்டாயம்.",
         source_url="https://pmksy.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-SHC",
         name_en="Soil Health Card Scheme",
         name_ta="மண் வள அட்டை திட்டம்", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="SHC", year="Ongoing",
         benefit_amount="Free soil testing and Soil Health Card with crop-wise nutrient and fertilizer recommendations",
         min_land_acres=0.0,
         documents_required=["Land records", "Farmer identification details"],
         documents_ta=["நில ஆவணங்கள்", "விவசாயி அடையாள விவரங்கள்"],
         application_url="https://soilhealth.dac.gov.in",
         description_en="Provides farmers with a Soil Health Card containing information on the nutrient status of their soil.",
         description_ta="விவசாயிகளுக்கு மண்ணின் ஊட்டச்சத்து நிலை மற்றும் பரிந்துரைக்கப்பட்ட உர அளவுகளை உள்ளடக்கிய மண் வள அட்டை இலவசமாக வழங்கப்படுகிறது.",
         eligibility_en="All farmers are eligible to receive a Soil Health Card for their landholding.",
         eligibility_ta="அனைத்து விவசாயிகளும் தங்கள் நிலத்திற்கு மண் வள அட்டை பெற தகுதியுடையவர்கள்.",
         source_url="https://soilhealth.dac.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-KCC",
         name_en="Kisan Credit Card (KCC)",
         name_ta="கிசான் கடன் அட்டை", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture (NABARD)",
         department_ta="வேளாண்மை அமைச்சகம் (நாபார்டு)",
         scheme_code="KCC", year="Ongoing",
         benefit_amount="Revolving short-term credit up to ₹5 lakh. Effective interest as low as ~4% per annum.",
         benefit_amount_num=500000.0, min_land_acres=0.0,
         documents_required=["Aadhaar card", "Land records or tenancy proof", "Two passport-size photographs", "Bank account details"],
         documents_ta=["ஆதார் அட்டை", "நில ஆவணங்கள் அல்லது குத்தகை சான்று", "இரண்டு பாஸ்போர்ட் அளவு புகைப்படங்கள்", "வங்கி கணக்கு விவரங்கள்"],
         application_url="https://www.jansamarth.in",
         description_en="Provides timely and adequate credit to farmers for agricultural and allied activities through a single-window revolving credit facility.",
         description_ta="விவசாயம் மற்றும் தொடர்புடைய செயல்பாடுகளுக்கு ஒற்றை சாளர சுழல் கடன் வசதி. ரூ.5 லட்சம் வரை கடன். சரியான நேரத்தில் திருப்பித் தந்தால் சுமார் 4% வட்டி.",
         eligibility_en="Small farmers, marginal farmers, sharecroppers, oral lessees and tenant farmers.",
         eligibility_ta="சிறு விவசாயிகள், குறு விவசாயிகள், குத்தகை விவசாயிகள், வாய்மொழி குத்தகைதாரர்கள்.",
         source_url="https://www.pib.gov.in/FactsheetDetails.aspx?Id=148600", last_verified=D, is_active=True),

    dict(scheme_id="CEN-ENAM",
         name_en="National Agriculture Market (e-NAM)",
         name_ta="தேசிய வேளாண் சந்தை (இ-நாம்)", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="e-NAM", year="Ongoing",
         benefit_amount="No direct cash benefit. Access to online trading platform for transparent price discovery.",
         min_land_acres=0.0,
         documents_required=["Aadhaar card", "Bank account details", "Mobile number for registration"],
         documents_ta=["ஆதார் அட்டை", "வங்கி கணக்கு விவரங்கள்", "பதிவுக்கான மொபைல் எண்"],
         application_url="https://www.enam.gov.in",
         description_en="Online trading platform linking APMC mandis nationwide for transparent price discovery.",
         description_ta="விவசாயிகளுக்கு விலை வெளிப்படைத்தன்மை மற்றும் நேரடி விற்பனை வாய்ப்பை வழங்கும் தேசிய ஆன்லைன் வர்த்தக தளம்.",
         eligibility_en="Farmers, traders and commission agents registered with a participating APMC regulated market.",
         eligibility_ta="பங்கேற்கும் APMC கட்டுப்படுத்தப்பட்ட சந்தையில் பதிவு செய்யப்பட்ட விவசாயிகள், வணிகர்கள் மற்றும் கமிஷன் முகவர்கள்.",
         source_url="https://www.enam.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-PKVY",
         name_en="Paramparagat Krishi Vikas Yojana (PKVY) - Organic Farming",
         name_ta="பாரம்பரிய வேளாண் வளர்ச்சித் திட்டம்", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="PKVY", year="Ongoing",
         benefit_amount="Financial assistance of Rs.6,000 per Hectare per year for 3 years.",
         min_land_acres=0.0,
         documents_required=["Aadhaar card", "Land records", "Bank account details"],
         documents_ta=["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்"],
         application_url="https://pgsindia-ncof.gov.in",
         description_en="Supports cluster-based organic farming through three-year financial support for certification, labeling, and FPO formation.",
         description_ta="கொத்து அணுகுமுறையில் அங்கக வேளாண்மையை ஊக்குவிக்கும் திட்டம். மூன்று ஆண்டுகளுக்கு ரூ.6,000/எக்டர்/ஆண்டு நிதி உதவி.",
         eligibility_en="Farmers willing to adopt or already practicing organic farming, organised into clusters.",
         eligibility_ta="அங்கக வேளாண்மை மேற்கொள்ள விரும்பும் விவசாயிகள். குழு அணுகுமுறை கட்டாயம்.",
         source_url="https://www.myscheme.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="CEN-PMKMY",
         name_en="PM Kisan Maan Dhan Yojana (Farmer Pension Scheme)",
         name_ta="பிரதம மந்திரி கிசான் மான்தன் திட்டம்", level="central", state="Tamil Nadu",
         department_en="Ministry of Agriculture and Farmers Welfare",
         department_ta="வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
         scheme_code="PM-KMY", year="Ongoing",
         benefit_amount="Assured monthly pension of ₹3,000 after age 60. Government matches farmer's monthly contribution.",
         benefit_amount_num=3000.0, min_land_acres=0.0, max_land_acres=5.0,
         documents_required=["Aadhaar card", "Land records", "Bank account or savings account details"],
         documents_ta=["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி சேமிப்பு கணக்கு விவரங்கள்"],
         application_url="https://maandhan.in",
         description_en="Voluntary contributory pension scheme for small and marginal farmers to receive ₹3,000/month pension after age 60.",
         description_ta="சிறு மற்றும் குறு விவசாயிகளுக்கான தன்னார்வ ஓய்வூதியத் திட்டம். 60 வயதிற்குப் பிறகு மாதம் ரூ.3,000 ஓய்வூதியம்.",
         eligibility_en="Small and marginal farmers aged 18 to 40 years with cultivable landholding up to 2 hectares.",
         eligibility_ta="18 முதல் 40 வயதுடைய சிறு மற்றும் குறு விவசாயிகள். 2 எக்டர் வரை பயிரிடும் நிலம். மாதாந்திர பங்களிப்பு தேவை.",
         source_url="https://www.myscheme.gov.in", last_verified=D, is_active=True),

    # ── State (level='state') ──────────────────────────────────────────────────
    dict(scheme_id="CEN-TNFR",
         name_en="Tamil Nadu Farmer Registry (AgriStack Farmer ID)",
         name_ta="தமிழ்நாடு விவசாயி பதிவு (விவசாயி அடையாள எண்)", level="state", state="Tamil Nadu",
         department_en="Agriculture (Tamil Nadu / AgriStack)",
         department_ta="வேளாண்மை (தமிழ்நாடு / AgriStack)",
         scheme_code="TNFR", year="Ongoing",
         benefit_amount="No direct cash benefit. Unique Farmer ID for seamless access to all schemes.",
         min_land_acres=0.0,
         documents_required=["Aadhaar card", "Chitta", "Adangal", "Patta", "Bank account details"],
         documents_ta=["ஆதார் அட்டை", "சிட்டா", "அடங்கல்", "பட்டா", "வங்கி கணக்கு விவரங்கள்"],
         application_url="https://tnfr.agristack.gov.in",
         description_en="Tamil Nadu's implementation of India's AgriStack Digital Agriculture Mission.",
         description_ta="இந்தியாவின் AgriStack டிஜிட்டல் வேளாண்மை திட்டத்தின் தமிழ்நாடு செயலாக்கம். ஆதார், நில ஆவணங்கள், பயிர் விவரங்கள் மற்றும் வங்கி கணக்குடன் இணைக்கப்பட்ட தனித்துவமான விவசாயி அடையாள எண்.",
         eligibility_en="Tamil Nadu farmers with land records (Chitta, Adangal, Patta).",
         eligibility_ta="சிட்டா, அடங்கல், பட்டா ஆவணங்களுடன் தமிழ்நாடு விவசாயிகள்.",
         source_url="https://tnfr.agristack.gov.in", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-147",
         name_en="Sub-Mission on Agricultural Mechanisation (Agri)",
         name_ta="வேளாண்மை இயந்திரமயமாக்கும் துணை இயக்கத்திட்டம்", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="SMAM", year="2023-24", source_scheme_id="147",
         min_land_acres=0.0,
         documents_required=["Patta", "Chitta", "Adangal"],
         documents_ta=["பட்டா", "அடங்கல்", "ஆதார் எண்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Increasing the reach of farm mechanization to small and marginal farmers to improve the farm power.",
         description_ta="வேளாண் இயந்திர சக்தியினை மேப்படுத்துவதற்காக, சிறு மற்றும் குறு விவசாயிகளிடையே வேளாண்மை இயந்திரமயமாக்குதலை ஊக்குவித்தல்.",
         eligibility_en="All District Farmer",
         eligibility_ta="அனைத்து மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-153",
         name_en="Chief Minister's Mannuyir Kaathu Mannuyir Kaappom Scheme",
         name_ta="முதலமைச்சரின் மண்ணுயிர் காத்து மன்னுயிர் காப்போம் திட்டம்", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="MMKMK", year="2024-25", source_scheme_id="153",
         min_land_acres=0.0,
         documents_required=["Aadhaar", "Patta", "Adangal"],
         documents_ta=["ஆதார் எண்", "பட்டா", "அடங்கல்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Promotes soil health through organic farming, vermicompost, green manure, bio-fertilizers, neem sapling distribution.",
         description_ta="உயிர்ம வேளாண் பண்ணைத் திடல் அமைத்தல், மண்புழு உரப்படுக்கைகள், பசுந்தாள் உர விதைகள், திரவ உயிர் உரங்கள், வேப்ப மரக்கன்றுகள் விநியோகம் மற்றும் இயற்கை இடுபொருள் மையம் அமைத்தல் ஆகியவை மூலம் மண்வளத்தை மேம்படுத்துகிறது.",
         eligibility_en="All Farmers", eligibility_ta="அனைத்து விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-162",
         name_en="Rainfed Area Development - Integrated Farming System 2024-25",
         name_ta="மானாவாரி பகுதி மேம்பாடு-ஒருங்கிணைந்த பண்ணையம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="RAD", year="2024-25", source_scheme_id="162",
         benefit_amount="50% subsidy up to Rs.30,000 per IFS unit", min_land_acres=0.0,
         documents_required=["Patta", "Adangal", "Aadhaar"],
         documents_ta=["பட்டா", "அடங்கல்", "ஆதார் எண்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Assistance for Crop component, Milch cow-1 / Goats(9+1), Fruit tree saplings, Apiary unit, vermi-compost Unit at 50 percent subsidy to the maximum of Rs.30,000/-",
         description_ta="பயிர் சாகுபடியுடன் கறவை மாடு/ஆடுகள், பழ மரக்கன்றுகள், தேனீ வளர்ப்பு, மண்புழு உரம் தயாரிப்பு ஆகியவற்றை மேற்கொள்ள 50% மானியம் அதிகபட்சமாக ரூ.30,000/- வழங்கப்படும்.",
         eligibility_en="Farmers of 28 Districts in Tamil Nadu", eligibility_ta="28 மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-163",
         name_en="National Agricultural Development Program (NADP) 2024-25",
         name_ta="தேசிய வேளாண் வளர்ச்சித் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="NADP", year="2024-25", source_scheme_id="163",
         benefit_amount="Varies by component (e.g., Rs.9,000/Ha for redgram transplantation at 50% subsidy)",
         min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
         documents_ta=["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "புகைப்படத்துடன் வங்கி கணக்கு புத்தகத்தின் முதல் பக்கம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Promotes maize cultivation area expansion, redgram transplantation technology, cotton cultivation and paddy production enhancement.",
         description_ta="மக்காச்சோள சாகுபடி விரிவாக்கம், நடவு துவரை திட்டம், பருத்தி சாகுபடி மற்றும் நெல் உற்பத்தியை மேம்படுத்துதல் ஆகியவை 2024-25 தேசிய வேளாண் வளர்ச்சி திட்டத்தின் கீழ் செயல்படுத்தப்படுகிறது.",
         eligibility_en="Varies by component; farmers in notified districts of Tamil Nadu",
         eligibility_ta="கூறுக்கு ஏற்ப மாறுபடும்; தமிழ்நாட்டில் அறிவிக்கப்பட்ட மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-164",
         name_en="Food and Nutrition Security Mission 2024-25",
         name_ta="உணவு மற்றும் ஊட்டச்சத்து பாதுகாப்பு இயக்கம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="FNSM", year="2024-25", source_scheme_id="164",
         benefit_amount="Varies by component (e.g., Rs.5,000/Ha cluster demo; Rs.8,500/Ha intercropping)",
         min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
         documents_ta=["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "புகைப்படத்துடன் வங்கி கணக்கு புத்தகத்தின் முதல் பக்கம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Promotes production of coarse cereals, nutri-cereals, cotton, sugarcane, pulses and rice through cluster demonstrations.",
         description_ta="மக்காச்சோளம், ஊட்டச்சத்து சிறுதானியங்கள், பருத்தி, கரும்பு, பயறுவகைகள் மற்றும் நெல் உற்பத்தியை ஊக்குவிக்கும் திட்டக் கூறுகள் தமிழ்நாட்டில் செயல்படுத்தப்படுகிறது.",
         eligibility_en="Farmers growing notified crops in eligible districts of Tamil Nadu",
         eligibility_ta="தமிழ்நாட்டில் தகுதியான மாவட்டங்களில் அறிவிக்கப்பட்ட பயிர்கள் பயிரிடும் விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-165",
         name_en="Tamil Nadu Millet Mission 2024-25",
         name_ta="தமிழ்நாடு சிறுதானிய இயக்கம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="TNMM", year="2024-25", source_scheme_id="165",
         min_land_acres=0.0,
         documents_required=["Aadhaar", "Chitta", "Adangal"],
         documents_ta=["ஆதார் அட்டை", "சிட்டா மற்றும் அடங்கல்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="To increase the production and productivity of Nutri Cereals across Tamil Nadu's 25 Millet Special Zone districts.",
         description_ta="ஊட்டச்சத்து மிக்க சிறுதானியங்களின் உற்பத்தி மற்றும் உற்பத்தித்திறனை அதிகரித்தல்.",
         eligibility_en="All farmers of all 25 Millet Special Zone districts",
         eligibility_ta="சிறுதானிய சிறப்பு மண்டலங்களின் 25 மாவட்டங்களில் உள்ள அனைத்து விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-167",
         name_en="Tamil Nadu Irrigated Agriculture Modernization Project (TNIAMP) 2024-25",
         name_ta="தமிழ்நாடு பாசன வேளாண்மை நவீனமயமாக்கல் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="TNIAMP", year="2024-25", source_scheme_id="167",
         min_land_acres=0.0,
         documents_required=["Aadhaar", "Patta", "Chitta", "Bank passbook"],
         documents_ta=["ஆதார்", "பட்டா", "சிட்டா", "வங்கி கணக்கு புத்தகம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Accelerates crop diversification from water-intensive to climate-resilient crops through hi-tech cultivation in 66 sub-basins. World Bank funded.",
         description_ta="உலகவங்கி நிதியுதவியில் 66 துணையாற்றுப்படுகைகளில் நீர் மேலாண்மை மற்றும் காலநிலை மாற்றத்திற்கு உகந்த பயிர் உற்பத்தி திறனை பெருக்குதல்.",
         eligibility_en="All Farmers in the Sub Basin only. Preference given to Small/Marginal, Women, SC/ST. Maximum 2 Ha per beneficiary.",
         eligibility_ta="துணையாற்றுப் படுகைகளில் உள்ள அனைத்து விவசாயிகளும். சிறு/குறு, பெண், தாழ்த்தப்பட்ட/பழங்குடி விவசாயிகளுக்கு முன்னுரிமை. அதிகபட்சம் 2 எக்டர்.",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-168",
         name_en="Sub-Mission on Seeds and Planting Materials 2024-25",
         name_ta="விதைகள் மற்றும் நடவுப் பொருட்களுக்கான துணை இயக்கத் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="SMSP", year="2024-25", source_scheme_id="168",
         min_land_acres=0.0,
         documents_required=["Chitta", "Aadhaar", "Ration Card"],
         documents_ta=["சிட்டா நகல்", "ஆதார் அட்டை நகல்", "குடும்ப அட்டை"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Production and distribution of foundation and certified seeds through Seed Village programme.",
         description_ta="விதை கிராமத் திட்டம் மூலம் நெல், பயறு, எண்ணெய்வித்து மற்றும் பிற பயிர்களுக்கான ஆதார மற்றும் சான்றிதழ் பெற்ற விதைகள் உற்பத்தி மற்றும் விநியோகம்.",
         eligibility_en="All farmers; seed farm registration required for seed production component",
         eligibility_ta="அனைத்து விவசாயிகளும்; விதை உற்பத்தி கூறுக்கு விதைப்பண்ணை பதிவு தேவை",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-171",
         name_en="Kalaignar All Village Integrated Agricultural Development Programme (KAVIADP) 2024-25",
         name_ta="கலைஞரின் அனைத்து கிராம ஒருங்கிணைந்த வேளாண் வளர்ச்சித் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="KAVIADP", year="2024-25", source_scheme_id="171",
         min_land_acres=0.0,
         documents_required=["Patta", "Chitta", "Adangal", "Ration card", "Aadhaar card photocopies"],
         documents_ta=["பட்டா", "சிட்டா", "அடங்கல்", "ரேசன் அட்டை மற்றும் ஆதார் அட்டை ஆவண நகல்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="To attain overall development in Agriculture and self-sufficiency in all villages of Tamil Nadu.",
         description_ta="அனைத்து கிராமங்களும் ஒட்டுமொத்த வேளாண் வளர்ச்சி மற்றும் தன்னிறைவு அடைந்திடும் நோக்கத்துடன் வேளாண்மை உழவர் நலத்துறை திட்டங்களுடன் ஒருங்கிணைத்து செயல்படுத்தப்படுகிறது.",
         eligibility_en="All families in the selected village panchayats",
         eligibility_ta="தேர்வு செய்யப்பட்ட கிராமத்தில் உள்ள அனைத்து குடும்பமும்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-172",
         name_en="National Mission on Edible Oils (NMEO) - Oilseeds 2024-25",
         name_ta="தேசிய சமையல் எண்ணெய் இயக்கம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="NMEO", year="2024-25", source_scheme_id="172",
         benefit_amount="50% subsidy on inputs (seeds, fertilizers, biocontrol agents)", min_land_acres=0.0,
         documents_required=["Aadhaar", "Bank passbook first page with photo", "Seed Farm registration details"],
         documents_ta=["ஆதார் கார்டு", "போட்டோவுடன் கூடிய வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம் மற்றும் விதைப்பண்ணை பதிவு விபரம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Cluster demonstrations, certified seeds, MN mixture, Liquid Biofertilizers, biocontrol agents, gypsum at 50% subsidy.",
         description_ta="எண்ணெய் வித்து பயிர்களில் தொகுப்பு செயல் விளக்கத் திடல்கள், சான்று விதைகள், நுண்ணூட்ட உரங்கள் 50 சதவீத மானியத்தில் செயல்படுத்தப்படுகிறது.",
         eligibility_en="All oilseed growing farmers in Tamil Nadu",
         eligibility_ta="எண்ணெய்வித்துப் பயிர் சாகுபடி செய்யும் விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-173",
         name_en="Rainfed Area Development - Integrated Farming System 2024-25",
         name_ta="மானாவாரி பகுதி மேம்பாடு - ஒருங்கிணைந்த பண்ணையம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="RAD-IFS", year="2024-25", source_scheme_id="173",
         benefit_amount="50% subsidy up to Rs.30,000 per IFS unit", min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
         documents_ta=["சிட்டா/அடங்கல்", "ஆதார் அட்டை", "வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Assistance for Crop component, Milch cow / Goats, Fruit tree saplings, Apiary unit, vermi-compost Unit at 50 percent subsidy to the maximum of Rs.30,000/-",
         description_ta="பயிர் சாகுபடியுடன் கறவை மாடு/ஆடுகள், பழ மரக்கன்றுகள், தேனீ வளர்ப்பு, மண்புழு உரம் தயாரிப்பு ஆகியவற்றை 50% மானியம் அதிகபட்சமாக ரூ.30,000/- வழங்கப்படும்.",
         eligibility_en="All Farmers of 29 Districts: Ariyalur, Coimbatore, Cuddalore, Dharmapuri, Dindigul, Karur, Krishnagiri, Kallakurichi, Vellore, Madurai, Namakkal, Perambalur, Ramanathapuram, Salem, Thoothukudi, Trichy, Tiruvannamalai, Villupuram, Virudhunagar, Sivagangai, Tiruppur, Ranipet, Thiruppathur, Thiruvarur, Tiruvallur, Erode, Thenkasi, Pudukottai and Theni",
         eligibility_ta="அரியலூர், கோயம்புத்தூர், கடலூர் உட்பட 29 மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-174",
         name_en="Paramparagat Krishi Vikas Yojana (PKVY) - Organic Farming 2024-25",
         name_ta="பாரம்பரிய வேளாண் வளர்ச்சி திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="PKVY", year="2024-25", source_scheme_id="174",
         benefit_amount="Rs.6,000 per Hectare per year for 3 years (Rs.2,000 in year 1)", min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
         documents_ta=["சிட்டா/அடங்கல்", "ஆதார் அட்டை", "வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Farmers interested in organic farming are organised into clusters and provided three-year financial support for certification, labeling, brand building, and FPO formation.",
         description_ta="அங்கக விவசாயத்தில் ஆர்வமுள்ள விவசாயிகளை குழுக்களாக ஒருங்கிணைத்து மூன்றாண்டுகள் நிதியுதவி வழங்கி அங்கக வேளாண்மை ஊக்குவிக்கப்படுகிறது. ஹெக்டேருக்கு ரூ.6,000/ஆண்டு.",
         eligibility_en="All District Farmers except Chennai and Nilgiris",
         eligibility_ta="சென்னை, நீலகிரி நீங்கலாக அனைத்து மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-175",
         name_en="State Agricultural Development Schemes (SADS) 2024-25",
         name_ta="மாநில வேளாண் வளர்ச்சித் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="SADS", year="2024-25", source_scheme_id="175",
         benefit_amount="50% subsidy on traditional paddy seeds; Rs.75 Lakh total allocation for 300MT seed distribution",
         min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar"],
         documents_ta=["சிட்டா", "அடங்கல்", "ஆதார் அட்டை"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Includes profitable cotton cultivation, area expansion in redgram, alternative crop cultivation, and traditional paddy variety seeds at 50% subsidy.",
         description_ta="பலன் தரும் பருத்தி சாகுபடி, துவரை பரப்பு விரிவாக்கம், மாற்றுப் பயிர் சாகுபடி, ஜிங்க் சல்பேட் மற்றும் ஜிப்சம் வழங்குதல் மற்றும் பாரம்பரிய நெல் ரகங்கள் 50% மானியத்தில் விநியோகம்.",
         eligibility_en="All Tamil Nadu farmers; 10 kg seeds per farmer for traditional paddy; priority to SC/ST small and marginal farmers",
         eligibility_ta="அனைத்து தமிழ்நாடு விவசாயிகள்; பாரம்பரிய நெல் விதை ஒரு விவசாயிக்கு 10 கிலோ",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-176",
         name_en="Chief Minister's Mannuyir Kaathu Mannuyir Kaappom Scheme 2024-25",
         name_ta="முதலமைச்சரின் மண்ணுயிர் காத்து மன்னுயிர் காப்போம் திட்டம் 2024-25", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="CMMKMK-25", year="2024-25", source_scheme_id="176",
         min_land_acres=0.0,
         documents_required=["Aadhaar", "Patta", "Adangal"],
         documents_ta=["ஆதார் எண்", "பட்டா", "அடங்கல்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Promotes soil health and organic farming through conservation of traditional pulses/millets, distribution of medicinal plant cuttings, organic farming model plots, neem saplings.",
         description_ta="பாரம்பரிய சிறுதானியம் மற்றும் பயறு பாதுகாத்தல், மருத்துவ தாவர நடவுப்பொருட்கள் விநியோகம், மாதிரி உயிர்ம வேளாண் திடல், வேப்ப மரக்கன்றுகள், மண்புழு உரம், பசுந்தாள் உரம் மற்றும் திரவ உயிர் உரங்கள் மூலம் மண்வளம் மேம்படுத்தல்.",
         eligibility_en="All Farmers in Tamil Nadu", eligibility_ta="அனைத்து விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),

    dict(scheme_id="TN-AGRI-177",
         name_en="Kuruvai Special Package 2024",
         name_ta="குறுவை சாகுபடி சிறப்புத் தொகுப்புத் திட்டம் 2024", level="state", state="Tamil Nadu",
         department_en="Agriculture", department_ta="வேளாண்மைத்துறை",
         scheme_code="KSP", year="2024-25", source_scheme_id="177",
         min_land_acres=0.0,
         documents_required=["Chitta", "Adangal", "Aadhaar", "Bank passbook"],
         documents_ta=["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "வங்கி கணக்கு புத்தகம்"],
         application_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en",
         description_en="Special package to support paddy cultivation during the Kuruvai (short-duration) season through input subsidies in delta districts.",
         description_ta="குறுவைப் பருவ நெல் சாகுபடியை ஊக்குவிக்க டெல்டா மாவட்டங்களில் விதை, உரம் மற்றும் பயிர் பாதுகாப்பு இடுபொருட்களுக்கு மானியம் வழங்கும் சிறப்புத் தொகுப்பு.",
         eligibility_en="Farmers in Tamil Nadu delta districts cultivating paddy during Kuruvai season",
         eligibility_ta="குறுவைப் பருவத்தில் நெல் சாகுபடி செய்யும் தமிழ்நாடு டெல்டா மாவட்ட விவசாயிகள்",
         source_url="https://www.tnagrisnet.tn.gov.in/home/schemes/en", last_verified=D, is_active=True),
]


async def main():
    async with SessionLocal() as db:
        for d in SCHEMES:
            stmt = pg_insert(GovernmentScheme).values(**d)
            # Upsert: update all content fields on conflict
            update_cols = {
                c: stmt.excluded[c]
                for c in d
                if c not in ("scheme_id",)
            }
            stmt = stmt.on_conflict_do_update(
                index_elements=["scheme_id"],
                set_=update_cols,
            )
            await db.execute(stmt)
        await db.commit()
    print(f"Seeded {len(SCHEMES)} schemes into main database.")
    await ENGINE.dispose()


if __name__ == "__main__":
    asyncio.run(main())
