"""Pillar 4 — Add enriched metadata columns; replace scheme catalog with 24-scheme dataset.

Revision ID: 005
Revises: 004
Create Date: 2026-06-17

Source of truth: Uzhavan AI Unified Agricultural Scheme Database
  - 9 Central schemes (level='central')
  - 15 Tamil Nadu State schemes from TNAGRISNET (level='state')
  Total: 24 schemes

Old schemes removed: CEN-PMKSY-PDMC, CEN-AIF, CEN-KUSUM,
  TN-TNFR, TN-UZHAVAR-SANTHAI, TN-MILLET-MISSION,
  TN-MANNUYIR, TN-KALAIGNAR-AVIADP, TN-HILL-FARMERS

New columns (all nullable, no existing data affected):
  department_en, department_ta, scheme_code, year,
  source_scheme_id, description_en, eligibility_en, source_url
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Scheme IDs from old seed (migration 004) that are superseded.
# ---------------------------------------------------------------------------
_OLD_IDS = (
    "CEN-PMKSY-PDMC",
    "CEN-AIF",
    "CEN-KUSUM",
    "TN-TNFR",
    "TN-UZHAVAR-SANTHAI",
    "TN-MILLET-MISSION",
    "TN-MANNUYIR",
    "TN-KALAIGNAR-AVIADP",
    "TN-HILL-FARMERS",
)

# ---------------------------------------------------------------------------
# Authoritative 24-scheme dataset (2026-06-17)
# Fields from JSON preserved verbatim.  Null values preserved as None.
# eligibility_rules (English) → eligibility_en column.
# documents_required_ta  → documents_ta column.
# level values normalised to lowercase to match schema validator pattern.
# ---------------------------------------------------------------------------
_SCHEMES = [
    # ── Central schemes (8 with level='central') ──────────────────────────
    {
        "scheme_id": "CEN-PMKISAN",
        "name_en": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "name_ta": "பிரதம மந்திரி கிசான் சம்மான் நிதி",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "PM-KISAN",
        "year": "Ongoing",
        "benefit_amount": "₹6,000 per year in three installments of ₹2,000 each via Direct Benefit Transfer",
        "description_en": "Provides direct income support to landholding farmer families to meet their agricultural and allied activity expenses. Fully funded by the Government of India.",
        "description_ta": "விவசாயக் குடும்பங்களுக்கு நேரடி வருமான உதவி. மூன்று தவணைகளில் ரூ.6,000 வழங்கப்படும்.",
        "eligibility_en": "Landholding farmer families (husband, wife, minor children) as per State/UT land records. Excludes income tax payers, constitutional post holders, institutional landholders, and professionals with higher income. Requires Aadhaar, e-KYC and land record validation.",
        "eligibility_ta": "நில உரிமையுள்ள விவசாய குடும்பங்கள். ஆதார் இணைப்பு மற்றும் e-KYC கட்டாயம்.",
        "documents_required": ["Aadhaar card", "Land ownership records (Patta/Chitta)", "Bank account (Aadhaar-seeded, NEFT enabled)"],
        "documents_ta": ["ஆதார் அட்டை", "நில உரிமை ஆவணங்கள் (பட்டா/சிட்டா)", "வங்கி கணக்கு (ஆதார் இணைப்புடன்)"],
        "application_url": "https://pmkisan.gov.in",
        "source_url": "https://pmkisan.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-PMFBY",
        "name_en": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "name_ta": "பிரதம மந்திரி பயிர் காப்பீட்டுத் திட்டம்",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "PMFBY",
        "year": "Ongoing",
        "benefit_amount": "Crop insurance coverage. Farmer premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial/horticultural crops. Government subsidises remaining premium.",
        "description_en": "Provides financial support to farmers suffering crop loss or damage due to natural calamities, pests and diseases. Voluntary for loanee and non-loanee farmers since 2020. Localised crop loss must be reported within 72 hours.",
        "description_ta": "இயற்கை சீற்றங்கள், பூச்சிகள் மற்றும் நோய்களால் பயிர் இழப்பு ஏற்படும் விவசாயிகளுக்கு நிதி உதவி. இழப்பு 72 மணி நேரத்தில் தெரிவிக்க வேண்டும்.",
        "eligibility_en": "All farmers growing notified crops in notified areas, including sharecroppers and tenant farmers. Voluntary participation. Crop must be notified under PMFBY for that season.",
        "eligibility_ta": "அறிவிக்கப்பட்ட பகுதிகளில் அறிவிக்கப்பட்ட பயிர்கள் பயிரிடும் அனைத்து விவசாயிகளும். குத்தகை விவசாயிகளும் தகுதியுடையவர்கள்.",
        "documents_required": ["Aadhaar card", "Land records or tenancy documents", "Bank account details", "Sowing certificate or crop declaration"],
        "documents_ta": ["ஆதார் அட்டை", "நில ஆவணங்கள் அல்லது குத்தகை ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்", "விதைப்பு சான்றிதழ் அல்லது பயிர் அறிவிப்பு"],
        "application_url": "https://pmfby.gov.in",
        "source_url": "https://pmfby.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-PMKSY",
        "name_en": "Pradhan Mantri Krishi Sinchayee Yojana - Per Drop More Crop (PMKSY-PDMC)",
        "name_ta": "பிரதம மந்திரி கிரிஷி சின்சாயி யோஜனா - நுண்ணீர் பாசனம்",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "PMKSY-PDMC",
        "year": "Ongoing",
        "benefit_amount": "Subsidy on drip and sprinkler micro-irrigation systems. Commonly reported at 55% and above; varies by farmer category and state. Small/Marginal farmers receive higher subsidy.",
        "description_en": "Promotes micro-irrigation (drip and sprinkler) to enhance water use efficiency at farm level under the 'Per Drop More Crop' philosophy. Achieves 40-80% water savings compared to conventional flood irrigation.",
        "description_ta": "சொட்டு நீர் மற்றும் தெளிப்பு நீர்ப்பாசனம் மூலம் நீர் பயன்பாட்டு திறனை மேம்படுத்துதல். வழக்கமான பாசனத்தை விட 40-80% நீர் சேமிப்பு சாத்தியம்.",
        "eligibility_en": "All farmers in States/UTs. Subsidy limited to 5 hectares per beneficiary. Only BIS-certified components permitted. Aadhaar mandatory for DBT-based benefit.",
        "eligibility_ta": "அனைத்து மாநிலங்களிலும் உள்ள விவசாயிகள். ஒரு பயனாளிக்கு அதிகபட்சம் 5 எக்டர். BIS சான்றளிக்கப்பட்ட கூறுகள் கட்டாயம்.",
        "documents_required": ["Aadhaar card", "Land records", "Bank account details", "Quotation for BIS-certified micro-irrigation equipment", "SF/MF certificate (for higher subsidy)", "Irrigation source certificate", "FMB sketch", "Passport size photo", "Water and soil analytical report"],
        "documents_ta": ["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்", "BIS சான்றளிக்கப்பட்ட நுண்ணீர்ப்பாசன உபகரணங்களுக்கான மேற்கோள்", "சிறு/குறு விவசாயி சான்றிதழ்"],
        "application_url": "https://pmksy.gov.in",
        "source_url": "https://pmksy.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-SHC",
        "name_en": "Soil Health Card Scheme",
        "name_ta": "மண் வள அட்டை திட்டம்",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "SHC",
        "year": "Ongoing",
        "benefit_amount": "Free soil testing and Soil Health Card with crop-wise nutrient and fertilizer recommendations",
        "description_en": "Provides farmers with a Soil Health Card containing information on the nutrient status of their soil along with recommended doses of fertilizers to improve soil health and fertility.",
        "description_ta": "விவசாயிகளுக்கு மண்ணின் ஊட்டச்சத்து நிலை மற்றும் பரிந்துரைக்கப்பட்ட உர அளவுகளை உள்ளடக்கிய மண் வள அட்டை இலவசமாக வழங்கப்படுகிறது.",
        "eligibility_en": "All farmers are eligible to receive a Soil Health Card for their landholding.",
        "eligibility_ta": "அனைத்து விவசாயிகளும் தங்கள் நிலத்திற்கு மண் வள அட்டை பெற தகுதியுடையவர்கள்.",
        "documents_required": ["Land records", "Farmer identification details"],
        "documents_ta": ["நில ஆவணங்கள்", "விவசாயி அடையாள விவரங்கள்"],
        "application_url": "https://soilhealth.dac.gov.in",
        "source_url": "https://soilhealth.dac.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-KCC",
        "name_en": "Kisan Credit Card (KCC)",
        "name_ta": "கிசான் கடன் அட்டை",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture (NABARD)",
        "department_ta": "வேளாண்மை அமைச்சகம் (நாபார்டு)",
        "scheme_code": "KCC",
        "year": "Ongoing",
        "benefit_amount": "Revolving short-term credit up to ₹5 lakh. Effective interest as low as ~4% per annum with prompt repayment incentive. Collateral waived up to ₹2 lakh.",
        "description_en": "Provides timely and adequate credit to farmers for agricultural and allied activities through a single-window revolving credit facility. Loan limit raised to ₹5 lakh under Modified Interest Subvention Scheme.",
        "description_ta": "விவசாயம் மற்றும் தொடர்புடைய செயல்பாடுகளுக்கு ஒற்றை சாளர சுழல் கடன் வசதி. ரூ.5 லட்சம் வரை கடன். சரியான நேரத்தில் திருப்பித் தந்தால் சுமார் 4% வட்டி.",
        "eligibility_en": "Small farmers, marginal farmers, sharecroppers, oral lessees and tenant farmers. SHGs and JLGs also eligible. KYC and bank account required.",
        "eligibility_ta": "சிறு விவசாயிகள், குறு விவசாயிகள், குத்தகை விவசாயிகள், வாய்மொழி குத்தகைதாரர்கள். சுய உதவிக் குழுக்கள் மற்றும் கூட்டுப் பொறுப்பு குழுக்களும் தகுதியுடையவை.",
        "documents_required": ["Aadhaar card", "Land records or tenancy proof", "Two passport-size photographs", "Bank account details"],
        "documents_ta": ["ஆதார் அட்டை", "நில ஆவணங்கள் அல்லது குத்தகை சான்று", "இரண்டு பாஸ்போர்ட் அளவு புகைப்படங்கள்", "வங்கி கணக்கு விவரங்கள்"],
        "application_url": "https://www.jansamarth.in",
        "source_url": "https://www.pib.gov.in/FactsheetDetails.aspx?Id=148600",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-ENAM",
        "name_en": "National Agriculture Market (e-NAM)",
        "name_ta": "தேசிய வேளாண் சந்தை (இ-நாம்)",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "e-NAM",
        "year": "Ongoing",
        "benefit_amount": "No direct cash benefit. Access to online trading platform for transparent price discovery and direct sale of produce.",
        "description_en": "Online trading platform linking APMC mandis nationwide for transparent price discovery and direct sale of agricultural produce, reducing dependence on intermediaries.",
        "description_ta": "விவசாயிகளுக்கு விலை வெளிப்படைத்தன்மை மற்றும் நேரடி விற்பனை வாய்ப்பை வழங்கும் தேசிய ஆன்லைன் வர்த்தக தளம்.",
        "eligibility_en": "Farmers, traders and commission agents registered with a participating APMC regulated market.",
        "eligibility_ta": "பங்கேற்கும் APMC கட்டுப்படுத்தப்பட்ட சந்தையில் பதிவு செய்யப்பட்ட விவசாயிகள், வணிகர்கள் மற்றும் கமிஷன் முகவர்கள்.",
        "documents_required": ["Aadhaar card", "Bank account details", "Mobile number for registration"],
        "documents_ta": ["ஆதார் அட்டை", "வங்கி கணக்கு விவரங்கள்", "பதிவுக்கான மொபைல் எண்"],
        "application_url": "https://www.enam.gov.in",
        "source_url": "https://www.enam.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-PKVY",
        "name_en": "Paramparagat Krishi Vikas Yojana (PKVY) - Organic Farming",
        "name_ta": "பாரம்பரிய வேளாண் வளர்ச்சித் திட்டம்",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "PKVY",
        "year": "Ongoing",
        "benefit_amount": "Financial assistance of Rs.6,000 per Hectare per year for 3 years (Rs.2,000 in the first year) for organic farming certification and promotion.",
        "description_en": "Supports cluster-based organic farming through capacity building, direct incentives for conversion to organic farming, three-year financial support for certification, labeling, and FPO formation under NPOP or PGS.",
        "description_ta": "கொத்து அணுகுமுறையில் அங்கக வேளாண்மையை ஊக்குவிக்கும் திட்டம். மூன்று ஆண்டுகளுக்கு ரூ.6,000/எக்டர்/ஆண்டு நிதி உதவி.",
        "eligibility_en": "Farmers willing to adopt or already practicing organic farming, organised into clusters. Specific cluster and area norms apply.",
        "eligibility_ta": "அங்கக வேளாண்மை மேற்கொள்ள விரும்பும் விவசாயிகள். குழு அணுகுமுறை கட்டாயம்.",
        "documents_required": ["Aadhaar card", "Land records", "Bank account details"],
        "documents_ta": ["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி கணக்கு விவரங்கள்"],
        "application_url": "https://pgsindia-ncof.gov.in",
        "source_url": "https://www.myscheme.gov.in",
        "source_scheme_id": None,
    },
    {
        "scheme_id": "CEN-PMKMY",
        "name_en": "PM Kisan Maan Dhan Yojana (Farmer Pension Scheme)",
        "name_ta": "பிரதம மந்திரி கிசான் மான்தன் திட்டம்",
        "level": "central",
        "state": "Tamil Nadu",
        "department_en": "Ministry of Agriculture and Farmers Welfare",
        "department_ta": "வேளாண்மை மற்றும் விவசாயிகள் நலன் அமைச்சகம்",
        "scheme_code": "PM-KMY",
        "year": "Ongoing",
        "benefit_amount": "Assured monthly pension of ₹3,000 after age 60. Government matches farmer's monthly contribution.",
        "description_en": "Voluntary contributory pension scheme for small and marginal farmers. Farmers aged 18-40 contribute a monthly amount (matched by Government) to receive ₹3,000/month pension after age 60.",
        "description_ta": "சிறு மற்றும் குறு விவசாயிகளுக்கான தன்னார்வ ஓய்வூதியத் திட்டம். 60 வயதிற்குப் பிறகு மாதம் ரூ.3,000 ஓய்வூதியம்.",
        "eligibility_en": "Small and marginal farmers aged 18 to 40 years with cultivable landholding up to 2 hectares. Monthly contribution required; government matches it.",
        "eligibility_ta": "18 முதல் 40 வயதுடைய சிறு மற்றும் குறு விவசாயிகள். 2 எக்டர் வரை பயிரிடும் நிலம். மாதாந்திர பங்களிப்பு தேவை.",
        "documents_required": ["Aadhaar card", "Land records", "Bank account or savings account details"],
        "documents_ta": ["ஆதார் அட்டை", "நில ஆவணங்கள்", "வங்கி சேமிப்பு கணக்கு விவரங்கள்"],
        "application_url": "https://maandhan.in",
        "source_url": "https://www.myscheme.gov.in",
        "source_scheme_id": None,
    },
    # ── State-level (level='state') — CEN-TNFR is state-level implementation ─
    {
        "scheme_id": "CEN-TNFR",
        "name_en": "Tamil Nadu Farmer Registry (AgriStack Farmer ID)",
        "name_ta": "தமிழ்நாடு விவசாயி பதிவு (விவசாயி அடையாள எண்)",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture (Tamil Nadu / AgriStack)",
        "department_ta": "வேளாண்மை (தமிழ்நாடு / AgriStack)",
        "scheme_code": "TNFR",
        "year": "Ongoing",
        "benefit_amount": "No direct cash benefit. Unique Farmer ID linked to Aadhaar, land records, crop details and bank account — single identity for all central and state agricultural benefits.",
        "description_en": "Tamil Nadu's implementation of India's AgriStack Digital Agriculture Mission. Every Tamil Nadu farmer receives a unique Farmer ID linked to Aadhaar, land records (Chitta/Adangal/Patta), crop details and bank account for seamless access to all schemes.",
        "description_ta": "இந்தியாவின் AgriStack டிஜிட்டல் வேளாண்மை திட்டத்தின் தமிழ்நாடு செயலாக்கம். ஆதார், நில ஆவணங்கள், பயிர் விவரங்கள் மற்றும் வங்கி கணக்குடன் இணைக்கப்பட்ட தனித்துவமான விவசாயி அடையாள எண்.",
        "eligibility_en": "Tamil Nadu farmers with land records (Chitta, Adangal, Patta). Tenant and small/marginal farmers can seek assistance at KVK or Agriculture Department offices.",
        "eligibility_ta": "சிட்டா, அடங்கல், பட்டா ஆவணங்களுடன் தமிழ்நாடு விவசாயிகள். குத்தகை மற்றும் சிறு/குறு விவசாயிகள் KVK அல்லது வேளாண்மைத்துறை அலுவலகத்தில் உதவி பெறலாம்.",
        "documents_required": ["Aadhaar card", "Chitta", "Adangal", "Patta", "Bank account details"],
        "documents_ta": ["ஆதார் அட்டை", "சிட்டா", "அடங்கல்", "பட்டா", "வங்கி கணக்கு விவரங்கள்"],
        "application_url": "https://tnfr.agristack.gov.in",
        "source_url": "https://tnfr.agristack.gov.in",
        "source_scheme_id": None,
    },
    # ── TNAGRISNET State schemes (level='state') ───────────────────────────
    {
        "scheme_id": "TN-AGRI-147",
        "name_en": "Sub-Mission on Agricultural Mechanisation (Agri)",
        "name_ta": "வேளாண்மை இயந்திரமயமாக்கும் துணை இயக்கத்திட்டம்",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "SMAM",
        "year": "2023-24",
        "benefit_amount": None,
        "description_en": "Increasing the reach of farm mechanization to small and marginal farmers to improve the farm power.",
        "description_ta": "வேளாண் இயந்திர சக்தியினை மேப்படுத்துவதற்காக, சிறு மற்றும் குறு விவசாயிகளிடையே வேளாண்மை இயந்திரமயமாக்குதலை ஊக்குவித்தல்.",
        "eligibility_en": "All District Farmer",
        "eligibility_ta": "அனைத்து மாவட்ட விவசாயிகள்",
        "documents_required": ["Patta", "Chitta", "Adangal"],
        "documents_ta": ["பட்டா", "அடங்கல்", "ஆதார் எண்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "147",
    },
    {
        "scheme_id": "TN-AGRI-153",
        "name_en": "Chief Minister's Mannuyir Kaathu Mannuyir Kaappom Scheme",
        "name_ta": "முதலமைச்சரின் மண்ணுயிர் காத்து மன்னுயிர் காப்போம் திட்டம்",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "MMKMK",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "Promotes soil health through organic farming, vermicompost, green manure, bio-fertilizers, neem sapling distribution and establishment of organic input production centres.",
        "description_ta": "உயிர்ம வேளாண் பண்ணைத் திடல் அமைத்தல், மண்புழு உரப்படுக்கைகள், பசுந்தாள் உர விதைகள், திரவ உயிர் உரங்கள், வேப்ப மரக்கன்றுகள் விநியோகம் மற்றும் இயற்கை இடுபொருள் மையம் அமைத்தல் ஆகியவை மூலம் மண்வளத்தை மேம்படுத்துகிறது.",
        "eligibility_en": "All Farmers",
        "eligibility_ta": "அனைத்து விவசாயிகள்",
        "documents_required": ["Aadhaar", "Patta", "Adangal"],
        "documents_ta": ["ஆதார் எண்", "பட்டா", "அடங்கல்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "153",
    },
    {
        "scheme_id": "TN-AGRI-162",
        "name_en": "Rainfed Area Development - Integrated Farming System 2024-25",
        "name_ta": "மானாவாரி பகுதி மேம்பாடு-ஒருங்கிணைந்த பண்ணையம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "RAD",
        "year": "2024-25",
        "benefit_amount": "50% subsidy up to Rs.30,000 per IFS unit",
        "description_en": "Assistance for Crop component, Milch cow-1 / Goats(9+1), Fruit tree saplings, Apiary unit, vermi-compost Unit at 50 percent subsidy to the maximum of Rs.30,000/-",
        "description_ta": "பயிர் சாகுபடியுடன் கறவை மாடு/ஆடுகள், பழ மரக்கன்றுகள், தேனீ வளர்ப்பு, மண்புழு உரம் தயாரிப்பு ஆகியவற்றை மேற்கொள்ள 50% மானியம் அதிகபட்சமாக ரூ.30,000/- வழங்கப்படும்.",
        "eligibility_en": "Farmers of 28 Districts in Tamil Nadu",
        "eligibility_ta": "28 மாவட்ட விவசாயிகள்",
        "documents_required": ["Patta", "Adangal", "Aadhaar"],
        "documents_ta": ["பட்டா", "அடங்கல்", "ஆதார் எண்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "162",
    },
    {
        "scheme_id": "TN-AGRI-163",
        "name_en": "National Agricultural Development Program (NADP) 2024-25",
        "name_ta": "தேசிய வேளாண் வளர்ச்சித் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "NADP",
        "year": "2024-25",
        "benefit_amount": "Varies by component (e.g., Rs.9,000/Ha for redgram transplantation at 50% subsidy)",
        "description_en": "Promotes maize cultivation area expansion, redgram transplantation technology, cotton cultivation and paddy production enhancement with soil health sustenance across Tamil Nadu.",
        "description_ta": "மக்காச்சோள சாகுபடி விரிவாக்கம், நடவு துவரை திட்டம், பருத்தி சாகுபடி மற்றும் நெல் உற்பத்தியை மேம்படுத்துதல் ஆகியவை 2024-25 தேசிய வேளாண் வளர்ச்சி திட்டத்தின் கீழ் செயல்படுத்தப்படுகிறது.",
        "eligibility_en": "Varies by component; farmers in notified districts of Tamil Nadu",
        "eligibility_ta": "கூறுக்கு ஏற்ப மாறுபடும்; தமிழ்நாட்டில் அறிவிக்கப்பட்ட மாவட்ட விவசாயிகள்",
        "documents_required": ["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
        "documents_ta": ["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "புகைப்படத்துடன் வங்கி கணக்கு புத்தகத்தின் முதல் பக்கம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "163",
    },
    {
        "scheme_id": "TN-AGRI-164",
        "name_en": "Food and Nutrition Security Mission 2024-25",
        "name_ta": "உணவு மற்றும் ஊட்டச்சத்து பாதுகாப்பு இயக்கம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "FNSM",
        "year": "2024-25",
        "benefit_amount": "Varies by component (e.g., Rs.5,000/Ha cluster demo; Rs.8,500/Ha intercropping)",
        "description_en": "Promotes production of coarse cereals, nutri-cereals, cotton, sugarcane, pulses and rice through cluster demonstrations and input subsidies across Tamil Nadu districts.",
        "description_ta": "மக்காச்சோளம், ஊட்டச்சத்து சிறுதானியங்கள், பருத்தி, கரும்பு, பயறுவகைகள் மற்றும் நெல் உற்பத்தியை ஊக்குவிக்கும் திட்டக் கூறுகள் தமிழ்நாட்டில் செயல்படுத்தப்படுகிறது.",
        "eligibility_en": "Farmers growing notified crops in eligible districts of Tamil Nadu",
        "eligibility_ta": "தமிழ்நாட்டில் தகுதியான மாவட்டங்களில் அறிவிக்கப்பட்ட பயிர்கள் பயிரிடும் விவசாயிகள்",
        "documents_required": ["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
        "documents_ta": ["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "புகைப்படத்துடன் வங்கி கணக்கு புத்தகத்தின் முதல் பக்கம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "164",
    },
    {
        "scheme_id": "TN-AGRI-165",
        "name_en": "Tamil Nadu Millet Mission 2024-25",
        "name_ta": "தமிழ்நாடு சிறுதானிய இயக்கம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "TNMM",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "To increase the production and productivity of Nutri Cereals across Tamil Nadu's 25 Millet Special Zone districts.",
        "description_ta": "ஊட்டச்சத்து மிக்க சிறுதானியங்களின் உற்பத்தி மற்றும் உற்பத்தித்திறனை அதிகரித்தல்.",
        "eligibility_en": "All farmers of all 25 Millet Special Zone districts (Cuddalore, Villupuram, Kallakurichi, Vellore, Thiruvannamalai, Salem, Namakkal, Dharmapuri, Krishnagiri, Coimbatore, Tiruppur, Erode, Tiruchirapalli, Karur, Perambalur, Ariyalur, Pudukottai, Madurai, Theni, Dindigul, Ramanathapuram, Virudhunagar, Sivagangai, Tenkasi and Thoothukudi)",
        "eligibility_ta": "சிறுதானிய சிறப்பு மண்டலங்களின் 25 மாவட்டங்களில் உள்ள அனைத்து விவசாயிகள்",
        "documents_required": ["Aadhaar", "Chitta", "Adangal"],
        "documents_ta": ["ஆதார் அட்டை", "சிட்டா மற்றும் அடங்கல்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "165",
    },
    {
        "scheme_id": "TN-AGRI-167",
        "name_en": "Tamil Nadu Irrigated Agriculture Modernization Project (TNIAMP) 2024-25",
        "name_ta": "தமிழ்நாடு பாசன வேளாண்மை நவீனமயமாக்கல் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "TNIAMP",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "Accelerates crop diversification from water-intensive to climate-resilient crops through hi-tech cultivation and water conservation in 66 sub-basins. World Bank funded.",
        "description_ta": "உலகவங்கி நிதியுதவியில் 66 துணையாற்றுப்படுகைகளில் நீர் மேலாண்மை மற்றும் காலநிலை மாற்றத்திற்கு உகந்த பயிர் உற்பத்தி திறனை பெருக்குதல்.",
        "eligibility_en": "All Farmers in the Sub Basin only. Preference given to Small/Marginal, Women, SC/ST. Maximum 2 Ha per beneficiary.",
        "eligibility_ta": "துணையாற்றுப் படுகைகளில் உள்ள அனைத்து விவசாயிகளும். சிறு/குறு, பெண், தாழ்த்தப்பட்ட/பழங்குடி விவசாயிகளுக்கு முன்னுரிமை. அதிகபட்சம் 2 எக்டர்.",
        "documents_required": ["Aadhaar", "Patta", "Chitta", "Bank passbook"],
        "documents_ta": ["ஆதார்", "பட்டா", "சிட்டா", "வங்கி கணக்கு புத்தகம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "167",
    },
    {
        "scheme_id": "TN-AGRI-168",
        "name_en": "Sub-Mission on Seeds and Planting Materials 2024-25",
        "name_ta": "விதைகள் மற்றும் நடவுப் பொருட்களுக்கான துணை இயக்கத் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "SMSP",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "Production and distribution of foundation and certified seeds of paddy, pulses, oilseeds and other crops through Seed Village programme to improve seed replacement rate.",
        "description_ta": "விதை கிராமத் திட்டம் மூலம் நெல், பயறு, எண்ணெய்வித்து மற்றும் பிற பயிர்களுக்கான ஆதார மற்றும் சான்றிதழ் பெற்ற விதைகள் உற்பத்தி மற்றும் விநியோகம்.",
        "eligibility_en": "All farmers; seed farm registration required for seed production component",
        "eligibility_ta": "அனைத்து விவசாயிகளும்; விதை உற்பத்தி கூறுக்கு விதைப்பண்ணை பதிவு தேவை",
        "documents_required": ["Chitta", "Aadhaar", "Ration Card"],
        "documents_ta": ["சிட்டா நகல்", "ஆதார் அட்டை நகல்", "குடும்ப அட்டை"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "168",
    },
    {
        "scheme_id": "TN-AGRI-171",
        "name_en": "Kalaignar All Village Integrated Agricultural Development Programme (KAVIADP) 2024-25",
        "name_ta": "கலைஞரின் அனைத்து கிராம ஒருங்கிணைந்த வேளாண் வளர்ச்சித் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "KAVIADP",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "To attain overall development in Agriculture and self-sufficiency in all villages of Tamil Nadu, implemented integrating with all farmers welfare related department schemes.",
        "description_ta": "அனைத்து கிராமங்களும் ஒட்டுமொத்த வேளாண் வளர்ச்சி மற்றும் தன்னிறைவு அடைந்திடும் நோக்கத்துடன் வேளாண்மை உழவர் நலத்துறை திட்டங்களுடன் ஒருங்கிணைத்து செயல்படுத்தப்படுகிறது.",
        "eligibility_en": "All families in the selected village panchayats",
        "eligibility_ta": "தேர்வு செய்யப்பட்ட கிராமத்தில் உள்ள அனைத்து குடும்பமும்",
        "documents_required": ["Patta", "Chitta", "Adangal", "Ration card", "Aadhaar card photocopies"],
        "documents_ta": ["பட்டா", "சிட்டா", "அடங்கல்", "ரேசன் அட்டை மற்றும் ஆதார் அட்டை ஆவண நகல்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "171",
    },
    {
        "scheme_id": "TN-AGRI-172",
        "name_en": "National Mission on Edible Oils (NMEO) - Oilseeds 2024-25",
        "name_ta": "தேசிய சமையல் எண்ணெய் இயக்கம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "NMEO",
        "year": "2024-25",
        "benefit_amount": "50% subsidy on inputs (seeds, fertilizers, biocontrol agents)",
        "description_en": "Cluster demonstrations, certified seeds, MN mixture, Liquid Biofertilizers, biocontrol agents, gypsum, and assistance for intercropping of pulses in groundnut at 50% subsidy.",
        "description_ta": "எண்ணெய் வித்து பயிர்களில் தொகுப்பு செயல் விளக்கத் திடல்கள், சான்று விதைகள், நுண்ணூட்ட உரங்கள் 50 சதவீத மானியத்தில் செயல்படுத்தப்படுகிறது.",
        "eligibility_en": "All oilseed growing farmers in Tamil Nadu",
        "eligibility_ta": "எண்ணெய்வித்துப் பயிர் சாகுபடி செய்யும் விவசாயிகள்",
        "documents_required": ["Aadhaar", "Bank passbook first page with photo", "Seed Farm registration details"],
        "documents_ta": ["ஆதார் கார்டு", "போட்டோவுடன் கூடிய வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம் மற்றும் விதைப்பண்ணை பதிவு விபரம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "172",
    },
    {
        "scheme_id": "TN-AGRI-173",
        "name_en": "Rainfed Area Development - Integrated Farming System 2024-25",
        "name_ta": "மானாவாரி பகுதி மேம்பாடு - ஒருங்கிணைந்த பண்ணையம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "RAD-IFS",
        "year": "2024-25",
        "benefit_amount": "50% subsidy up to Rs.30,000 per IFS unit",
        "description_en": "Assistance for Crop component, Milch cow / Goats, Fruit tree saplings, Apiary unit, vermi-compost Unit at 50 percent subsidy to the maximum of Rs.30,000/-",
        "description_ta": "பயிர் சாகுபடியுடன் கறவை மாடு/ஆடுகள், பழ மரக்கன்றுகள், தேனீ வளர்ப்பு, மண்புழு உரம் தயாரிப்பு ஆகியவற்றை 50% மானியம் அதிகபட்சமாக ரூ.30,000/- வழங்கப்படும்.",
        "eligibility_en": "All Farmers of 29 Districts: Ariyalur, Coimbatore, Cuddalore, Dharmapuri, Dindigul, Karur, Krishnagiri, Kallakurichi, Vellore, Madurai, Namakkal, Perambalur, Ramanathapuram, Salem, Thoothukudi, Trichy, Tiruvannamalai, Villupuram, Virudhunagar, Sivagangai, Tiruppur, Ranipet, Thiruppathur, Thiruvarur, Tiruvallur, Erode, Thenkasi, Pudukottai and Theni",
        "eligibility_ta": "அரியலூர், கோயம்புத்தூர், கடலூர் உட்பட 29 மாவட்ட விவசாயிகள்",
        "documents_required": ["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
        "documents_ta": ["சிட்டா/அடங்கல்", "ஆதார் அட்டை", "வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "173",
    },
    {
        "scheme_id": "TN-AGRI-174",
        "name_en": "Paramparagat Krishi Vikas Yojana (PKVY) - Organic Farming 2024-25",
        "name_ta": "பாரம்பரிய வேளாண் வளர்ச்சி திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "PKVY",
        "year": "2024-25",
        "benefit_amount": "Rs.6,000 per Hectare per year for 3 years (Rs.2,000 in year 1)",
        "description_en": "Farmers interested in organic farming are organised into clusters and provided three-year financial support (Rs.6,000/Ha/year) for certification, labeling, brand building, and FPO formation under NPOP or PGS.",
        "description_ta": "அங்கக விவசாயத்தில் ஆர்வமுள்ள விவசாயிகளை குழுக்களாக ஒருங்கிணைத்து மூன்றாண்டுகள் நிதியுதவி வழங்கி அங்கக வேளாண்மை ஊக்குவிக்கப்படுகிறது. ஹெக்டேருக்கு ரூ.6,000/ஆண்டு.",
        "eligibility_en": "All District Farmers except Chennai and Nilgiris",
        "eligibility_ta": "சென்னை, நீலகிரி நீங்கலாக அனைத்து மாவட்ட விவசாயிகள்",
        "documents_required": ["Chitta", "Adangal", "Aadhaar", "Bank passbook first page with photo"],
        "documents_ta": ["சிட்டா/அடங்கல்", "ஆதார் அட்டை", "வங்கிக்கணக்கு புத்தகத்தின் முதல் பக்கம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "174",
    },
    {
        "scheme_id": "TN-AGRI-175",
        "name_en": "State Agricultural Development Schemes (SADS) 2024-25",
        "name_ta": "மாநில வேளாண் வளர்ச்சித் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "SADS",
        "year": "2024-25",
        "benefit_amount": "50% subsidy on traditional paddy seeds; Rs.75 Lakh total allocation for 300MT seed distribution",
        "description_en": "Includes profitable cotton cultivation, area expansion in redgram, alternative crop cultivation, distribution of ZnSO4 and Gypsum, and traditional paddy variety seeds at 50% subsidy. 300MT traditional paddy seeds distributed under Rs.75 Lakh subsidy.",
        "description_ta": "பலன் தரும் பருத்தி சாகுபடி, துவரை பரப்பு விரிவாக்கம், மாற்றுப் பயிர் சாகுபடி, ஜிங்க் சல்பேட் மற்றும் ஜிப்சம் வழங்குதல் மற்றும் பாரம்பரிய நெல் ரகங்கள் 50% மானியத்தில் விநியோகம்.",
        "eligibility_en": "All Tamil Nadu farmers; 10 kg seeds per farmer for traditional paddy; priority to SC/ST small and marginal farmers",
        "eligibility_ta": "அனைத்து தமிழ்நாடு விவசாயிகள்; பாரம்பரிய நெல் விதை ஒரு விவசாயிக்கு 10 கிலோ; ஆதிதிராவிடர்/பழங்குடியின சிறு/குறு விவசாயிகளுக்கு முன்னுரிமை",
        "documents_required": ["Chitta", "Adangal", "Aadhaar"],
        "documents_ta": ["சிட்டா", "அடங்கல்", "ஆதார் அட்டை"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "175",
    },
    {
        "scheme_id": "TN-AGRI-176",
        "name_en": "Chief Minister's Mannuyir Kaathu Mannuyir Kaappom Scheme 2024-25",
        "name_ta": "முதலமைச்சரின் மண்ணுயிர் காத்து மன்னுயிர் காப்போம் திட்டம் 2024-25",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "CMMKMK-25",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "Promotes soil health and organic farming through conservation of traditional pulses/millets, distribution of medicinal plant cuttings, organic farming model plots, neem saplings, vermicompost, green manure and liquid bio-fertilizers.",
        "description_ta": "பாரம்பரிய சிறுதானியம் மற்றும் பயறு பாதுகாத்தல், மருத்துவ தாவர நடவுப்பொருட்கள் விநியோகம், மாதிரி உயிர்ம வேளாண் திடல், வேப்ப மரக்கன்றுகள், மண்புழு உரம், பசுந்தாள் உரம் மற்றும் திரவ உயிர் உரங்கள் மூலம் மண்வளம் மேம்படுத்தல்.",
        "eligibility_en": "All Farmers in Tamil Nadu",
        "eligibility_ta": "அனைத்து விவசாயிகள்",
        "documents_required": ["Aadhaar", "Patta", "Adangal"],
        "documents_ta": ["ஆதார் எண்", "பட்டா", "அடங்கல்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "176",
    },
    {
        "scheme_id": "TN-AGRI-177",
        "name_en": "Kuruvai Special Package 2024",
        "name_ta": "குறுவை சாகுபடி சிறப்புத் தொகுப்புத் திட்டம் 2024",
        "level": "state",
        "state": "Tamil Nadu",
        "department_en": "Agriculture",
        "department_ta": "வேளாண்மைத்துறை",
        "scheme_code": "KSP",
        "year": "2024-25",
        "benefit_amount": None,
        "description_en": "Special package to support paddy cultivation during the Kuruvai (short-duration) season through input subsidies for seeds, fertilizers and crop protection in delta districts.",
        "description_ta": "குறுவைப் பருவ நெல் சாகுபடியை ஊக்குவிக்க டெல்டா மாவட்டங்களில் விதை, உரம் மற்றும் பயிர் பாதுகாப்பு இடுபொருட்களுக்கு மானியம் வழங்கும் சிறப்புத் தொகுப்பு.",
        "eligibility_en": "Farmers in Tamil Nadu delta districts cultivating paddy during Kuruvai season",
        "eligibility_ta": "குறுவைப் பருவத்தில் நெல் சாகுபடி செய்யும் தமிழ்நாடு டெல்டா மாவட்ட விவசாயிகள்",
        "documents_required": ["Chitta", "Adangal", "Aadhaar", "Bank passbook"],
        "documents_ta": ["சிட்டா", "அடங்கல்", "ஆதார் அட்டை", "வங்கி கணக்கு புத்தகம்"],
        "application_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_url": "https://www.tnagrisnet.tn.gov.in/home/schemes/en",
        "source_scheme_id": "177",
    },
]


def _pg_array(items: list | None) -> str:
    """Convert Python list to PostgreSQL text[] literal string."""
    if not items:
        return "{}"
    parts = []
    for s in items:
        # Escape backslashes then double-quotes for PG array literal
        s = str(s).replace("\\", "\\\\").replace('"', '\\"')
        parts.append(f'"{s}"')
    return "{" + ",".join(parts) + "}"


_UPSERT_SQL = sa.text("""
    INSERT INTO government_schemes (
        scheme_id, name_en, name_ta, level, state,
        benefit_amount,
        min_land_acres,
        requires_aadhaar,
        documents_required,
        documents_ta,
        application_url,
        department_en, department_ta,
        scheme_code, year, source_scheme_id,
        description_en, description_ta,
        eligibility_en, eligibility_ta,
        source_url,
        last_verified, is_active
    ) VALUES (
        :scheme_id, :name_en, :name_ta, :level, :state,
        :benefit_amount,
        0.0,
        FALSE,
        CAST(:documents_required AS text[]),
        CAST(:documents_ta AS text[]),
        :application_url,
        :department_en, :department_ta,
        :scheme_code, :year, :source_scheme_id,
        :description_en, :description_ta,
        :eligibility_en, :eligibility_ta,
        :source_url,
        '2026-06-17', TRUE
    )
    ON CONFLICT (scheme_id) DO UPDATE SET
        name_en           = EXCLUDED.name_en,
        name_ta           = EXCLUDED.name_ta,
        level             = EXCLUDED.level,
        state             = EXCLUDED.state,
        benefit_amount    = EXCLUDED.benefit_amount,
        documents_required = EXCLUDED.documents_required,
        documents_ta      = EXCLUDED.documents_ta,
        application_url   = EXCLUDED.application_url,
        department_en     = EXCLUDED.department_en,
        department_ta     = EXCLUDED.department_ta,
        scheme_code       = EXCLUDED.scheme_code,
        year              = EXCLUDED.year,
        source_scheme_id  = EXCLUDED.source_scheme_id,
        description_en    = EXCLUDED.description_en,
        description_ta    = EXCLUDED.description_ta,
        eligibility_en    = EXCLUDED.eligibility_en,
        eligibility_ta    = EXCLUDED.eligibility_ta,
        source_url        = EXCLUDED.source_url,
        last_verified     = EXCLUDED.last_verified,
        is_active         = EXCLUDED.is_active,
        updated_at        = now()
""")


def upgrade() -> None:
    # Step 1 — Add new nullable columns (all safe; no existing data affected)
    op.add_column("government_schemes", sa.Column("department_en", sa.String(200), nullable=True))
    op.add_column("government_schemes", sa.Column("department_ta", sa.String(200), nullable=True))
    op.add_column("government_schemes", sa.Column("scheme_code", sa.String(30), nullable=True))
    op.add_column("government_schemes", sa.Column("year", sa.String(20), nullable=True))
    op.add_column("government_schemes", sa.Column("source_scheme_id", sa.String(20), nullable=True))
    op.add_column("government_schemes", sa.Column("description_en", sa.Text(), nullable=True))
    op.add_column("government_schemes", sa.Column("eligibility_en", sa.Text(), nullable=True))
    op.add_column("government_schemes", sa.Column("source_url", sa.String(500), nullable=True))

    conn = op.get_bind()

    # Step 2 — Remove superseded scheme IDs (cascades to eligibility_results FK)
    placeholders = ",".join(f"'{sid}'" for sid in _OLD_IDS)
    conn.execute(sa.text(f"DELETE FROM government_schemes WHERE scheme_id IN ({placeholders})"))

    # Step 3 — Upsert all 24 authoritative schemes
    for scheme in _SCHEMES:
        conn.execute(
            _UPSERT_SQL,
            {
                **{k: v for k, v in scheme.items() if k not in ("documents_required", "documents_ta")},
                "documents_required": _pg_array(scheme.get("documents_required")),
                "documents_ta": _pg_array(scheme.get("documents_ta")),
            },
        )


def downgrade() -> None:
    conn = op.get_bind()
    # Remove the 24 new schemes
    new_ids = ",".join(f"'{s['scheme_id']}'" for s in _SCHEMES)
    conn.execute(sa.text(f"DELETE FROM government_schemes WHERE scheme_id IN ({new_ids})"))

    # Drop added columns
    for col in ("department_en", "department_ta", "scheme_code", "year",
                "source_scheme_id", "description_en", "eligibility_en", "source_url"):
        op.drop_column("government_schemes", col)
